### ISSUE TITLE
Update to xtext 2.11

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#28]
Migrate to xtext 2.11 so that we can officially support vscode.

Release Date: 
Tuesday, October 18, 2016

**Comment by colameo** [comment]
Agree to that, as soon xtext is stable enough we should move to it

**Comment by cbornet** [comment]
Oops ! Hofstadter's Law strikes again : https://blogs.itemis.com/en/xtext-2.11-release-plan-changed

**Comment by cbornet** [comment]
New date : January 24th 2017 http://typefox.io/xtext-2-11-beta-1-is-here

**Comment by cbornet** [comment]
They say there's a beta but it's not tagged...

**Comment by jbadeau** [comment]
So shall we wait till then or do a release soon?

**Comment by cbornet** [comment]
I'd say wait till then for merge on master.
Meanwhile we could build a vscode extension from the vscode branch and tag it as beta.
cc @jdubois

**Comment by colameo** [comment]
2.11 beta release is actually not so stable... let's wait as @cbornet suggested.

**Comment by cbornet** [comment]
I propose to publish the vscode-beta extension at the same time as the 1.0.0 release of the IDEA/Eclipse plugins. OK with that ?

**Comment by cbornet** [comment]
We'll ask for estimates and treat them as deadlines...

**Comment by colameo** [comment]
will start Friday with the migration to 2.11. I do not expect much work todo... however, estimates are anyway difficult to make... especially in projects which I do in my free time :-)

**Comment by cbornet** [comment]
@colameo I was talking about xtext 2.11 release which was a bit late 😄 
Funny thing is that they released just 2 hours after my comment. I feel so powerful !

**Comment by colameo** [comment]
hope we can merge soon and have one code base for all supported IDE platforms. I've also started to make some experiments with Xtext and Che...

**Comment by colameo** [comment]
ok, projects (JDL + Xdocker) are now migrated to xtext 2.11 and I've merged my changes to master.
@cbornet can u please merge your vscode plugin to the JDL project folder?

**Comment by cbornet** [comment]
yes. will do.

**Comment by cbornet** [comment]
I don't find the vscode branch anymore ! Was it deleted ?

**Comment by cbornet** [comment]
I got back the latest commit I did from https://github.com/cbornet/jdl/commits/deba37bbe0b18e1539e4071a54384528641c2a23 . Do you know how to restore the branch from this commit ?

**Comment by cbornet** [comment]
I managed to recover the branch from the commit locally.
@colameo is the project migrated to xtext 2.11 ? I still see version 2.10.0 in [build.gradle](https://github.com/jhipster/jhipster-ide/blob/master/jdl/build.gradle#L12)

**Comment by cbornet** [comment]
It seems only the Maven pom was updated.

**Comment by cbornet** [comment]
Are you using Maven or Gradle to build the project ? If only Maven is used, I think it would be better to remove everything gradle-related.
I would also need to figure how to build the vscode with Maven as the example I followed was bsed on gradle.

**Comment by jbadeau** [comment]
The idea plugin cannot be built with maven at the moment 😞

**Comment by colameo** [comment]
@cbornet thanks for your work!
